### ISSUE TITLE
Flutter Bluetooth Setup missing?

### ISSUE THREAD

**Issue by triple-it** [MuhammedZek/blu_chat#1]
Hi! Greate guide!

Maybe we are missing a step to setup Bluetooth support in flutter?
~~
2022-04-09 01:03:56.219563+0200 Runner[5452:2714842] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestEnable on channel flutter_bluetooth_serial/methods)
~~

**Comment by triple-it** [comment]
Also I noticed the following

```
The plugin `flutter_bluetooth_serial` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

```

**Comment by triple-it** [comment]
This is the command output

```
roderickgroesbeek@Rodericks-MacBook-Air blu_chat % flutter run
Multiple devices found:
Android SDK built for x86 (mobile) • emulator-5554             • android-x86 • Android 11 (API 30) (emulator)
Unk's iPhone11 in gebruik (mobile) • 00008030-XXXXXXXXXXX • ios         • iOS 14.8.1 18H107
[1]: Android SDK built for x86 (emulator-5554)
[2]: Unk's iPhone11 in gebruik (00008030-000A69D0110A802E)
Please choose one (To quit, press "q/Q"): 2
The plugin `flutter_bluetooth_serial` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a
future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib/main.dart on Unk's iPhone11 in gebruik in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: YYYYYYYYY
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.0s
Xcode build done.                                           17.8s
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getState on channel flutter_bluetooth_serial/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      FlutterBluetoothSerial.state (package:flutter_bluetooth_serial/FlutterBluetoothSerial.dart:48:80)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method isEnabled on channel flutter_bluetooth_serial/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      FlutterBluetoothSerial.isEnabled (package:flutter_bluetooth_serial/FlutterBluetoothSerial.dart:36:39)
<asynchronous suspension>
#2      _MainPage.initState.<anonymous closure> (package:flutter_blue_app/MainPage.dart:35:11)
<asynchronous suspension>
#3      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:12)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getName on channel flutter_bluetooth_serial/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
Installing and launching...                                        22.3s
Syncing files to device Unk's iPhone11 in gebruik...               159ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on Unk's iPhone11 in gebruik is available at: http://127.0.0.1:64402/0laRXeF48e0=/
The Flutter DevTools debugger and profiler on Unk's iPhone11 in gebruik is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:64402/0laRXeF48e0=/
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestEnable on channel flutter_bluetooth_serial/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      FlutterBluetoothSerial.requestEnable (package:flutter_bluetooth_serial/FlutterBluetoothSerial.dart:78:41)
<asynchronous suspension>
#2      _MainPage.build.<anonymous closure>.future (package:flutter_blue_app/MainPage.dart:98:21)
<asynchronous suspension>

```

**Comment by triple-it** [comment]
Hi.. I researched and found the following Github issue
[https://github.com/edufolly/flutter_bluetooth_serial/issues/2](url)

Here is stated that IOS is not supported in this used library
